name: readability
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.3
  - jupyter
  - altair
  - seaborn
  - openpyxl
  - python-docx
  - streamlit
  - icecream
  - textstat
  - textblob
  - mkdocs
